include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_use_package_imports: true
    prefer_single_quotes: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_null_aware_method_calls: true
    avoid_multiple_declarations_per_line: true
    avoid_redundant_argument_values: true
    avoid_slow_async_io: true
    avoid_types_on_closure_parameters: true
    avoid_positional_boolean_parameters: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_type_to_string: true
    unnecessary_breaks: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_null_checks: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    use_colored_box: true
    use_decorated_box: true
    use_string_buffers: true
    unawaited_futures: true
    discarded_futures: true
    cancel_subscriptions: true
    require_trailing_commas: true
    unnecessary_await_in_return: true
    only_throw_errors: true
    cast_nullable_to_non_nullable: true
    close_sinks: true
    deprecated_consistency: true
    library_names: true
    literal_only_boolean_expressions: true
    matching_super_parameters: true
    missing_whitespace_between_adjacent_strings: true
    no_literal_bool_comparisons: true
    omit_local_variable_types: true
    parameter_assignments: true
    sized_box_shrink_expand: true
    throw_in_finally: true
